blank_issues_enabled: true
contact_links:
  - name: How to add a file type
    url: https://github.com/Jeramai/shortcut3ds/blob/main/CONTRIBUTING.md#add-a-file-type
    about: The guide for contributors
